feat(docs): add database e-r diagram
Sergih28/groc pull request #175
Opened 2024-03-24 08:55 UTC by ehdlg

## What type of PR is this? (Check all applicable)

- [ ] 🚀 Feature
- [ ] 🐛 Bug Fix
- [ ] 📚 Documentation
- [ ] 💻 Blog post
- [ ] 🎨 Styles
- [ ] 🛠️ Refactoring
- [ ] 🕵️‍♀️ Code Review
- [ ] 🚑 Hotfix
- [ ] 🧪 Test
- [ ] 🌐 Localization/Internationalization
- [ ] ⚙️  Configuration and Environment
- [ ] 🚫 Deprecation or Removal
- [ ] 📦 Release
- [ ] ⏪ Revert

## Description

**Please describe the changes in this pull request:**

Replace this text with a clear and concise description of what you've done.

## Related Issues

Please link related issues by removing lines that are not applicable.

- Fixes #123
- Addresses #456

## Checklist

**Before submitting this pull request, please make sure you have done the following:**

### Code Quality

- [ ] Reviewed your code for any potential issues.
- [ ] Checked for coding style and formatting.

### Updated documentation?

- [ ] ✅ Yes
- [ ] 🙅 No, because there is nothing to update
- [ ] 🙋‍♂️ No, I need help

### Added tests for your changes?

- [ ] ✅ Yes
- [ ] 🙅 No, because they are not needed
- [ ] 🙋‍♂️ No, I need help

### UI Changes

- [ ] Added screenshots or recordings to demonstrate UI-related changes (if applicable).

## Additional Information

Replace this text with any additional information.

2024-03-25 21:16 UTC, Sergih28 requested changes

2024-03-25 21:16 UTC, Sergih28 commented on docs/database.md
> +
Can you remove this empty line please?

2024-03-26 06:28 UTC, ehdlg commented on docs/database.md
> +
Done.

2024-03-26 10:07 UTC, Sergih28 approved these changes

2024-03-26 10:07 UTC, merged